### ISSUE TITLE
client version 1.22 is too old

### ISSUE THREAD

**Issue by johannesbrunner-wd** [GoogleContainerTools/container-diff#144]
The tool seems not to work on windows 10 at all.
`.\container-diff.exe analyze daemon://ca0e3f38e555`
Retrieving image ca0e3f38e555:latest from source Local Daemon
ERRO[0000] Error loading image from docker engine: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
ERRO[0000] Error processing image: Error loading image from docker engine: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

I think I have version 1.32 which is higher than 1.22 and 1.24 either.

docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:50:27 2017
 OS/Arch:      windows/amd64
 Experimental: true

**Comment by dlorenc** [comment]
We should be defaulting to 1.32 as far as I can tell - https://github.com/GoogleCloudPlatform/container-diff/blob/master/vendor/github.com/docker/docker/api/common.go#L18

Do you happen to have an environment variable `DOCKER_API_VERSION` set? I'm not sure what would be forcing this to use an older version.

**Comment by johannesbrunner-wd** [comment]
I am sorry. I have no requested env variable set.
I tried this on serveral other machines, some with windows 10 and some with windows 2016 server installed and everywhere the same error message.

> client version 1.22 is too old.

**Comment by r2d4** [comment]
I think 1.22 (docker 1.9) might be too old.  Can you make sure that you're running at least docker 1.11?

**Comment by johannesbrunner-wd** [comment]
Sorry @r2d4, I have no idea what you are talking about?
Can you provide more details. I posted in the first statement my version and thougth:
docker 17.09 is a greater version than 1.9
API version 1.32 is a greater version than 1.22
As far as I know there is no version I could update to, because this is the latest.

**Comment by r2d4** [comment]
@johannesbrunner-wd Sorry I didn't read the issue close enough, didn't see that you were actually on a very recent version.  We do have some code to do the API negotiation between the client and the server, so its possible that we need to upgrade that code so that the most recent versions can be recognized.

**Comment by nkubala** [comment]
@johannesbrunner-wd could you try the latest version and see if this is still an issue?

**Comment by johannesbrunner-wd** [comment]
I retried and there is still in issue, even if the issue changed. 
called once more
>  .\container-diff-windows-amd64.exe analyze daemon://38cf305e4131

instead of client version 1.22 is too old the error is now.

> .\container-diff-windows-amd64.exe analyze daemon://38cf305e4131
> Retrieving image 38cf305e4131:latest from source Local Daemon
> [31mERRO[0m[0000] Error processing image: Error loading image from docker engine: error during connect: Get https://%2F%2F.%2Fpipe%2Fdocker_engine/v1.22/images/get?names=38cf305e4131%3Alatest: dial
> tcp: lookup //./pipe/docker_engine: no such host
> 

see this [issue ](https://github.com/Microsoft/Docker.DotNet/issues/109)and related issued for more information.

**Comment by johannesbrunner-wd** [comment]
Hi, using a fully qualified image name does not resolve the issue. Same problem as with image id.

**Comment by nkubala** [comment]
@johannesbrunner-wd what's the latest here? Could you pull the latest binary and see if you're still having this issue? I ran into something similar a little while ago on OS X, and was able to fix it by setting the `DOCKER_API_VERSION` environment variable
