### ISSUE TITLE
Don't exit with 0 if images are different

### ISSUE THREAD

**Issue by bodgit** [GoogleContainerTools/container-diff#192]
This tool seems to always exit 0 when I run  `container-diff diff ...` on two images that are different. A common convention in diff tools is to exit 0 when there are no differences, 1 when there are differences and 2 when an error occurred.

This would make it simple to use in shell scripts or build pipelines; I don't want to parse the output to discern if there are differences, in fact I probably don't even care about the output at all, I just want to be able to do something like `container-diff diff <img1> <img2> || ...`.

See also the `--exit-code` option for `git diff` so having something implied by setting `--quiet` in #175 could work.

**Comment by tejal29** [comment]
We are working on a common CLI Lib for all our tools and this will be a good feature to add in there.

**Comment by moschlar** [comment]
Any news on this?

**Comment by denisbr** [comment]
Using this tool for what I wanted is a lot harder due to this issue still not being fixed.
A good diff-tool allows one to quickly identify if the compared objects are identical, and container-diff makes it a lot more convoluted to evaluate this.

**Comment by Reamer** [comment]
Why did you close the issue? Is there a solution? If not, can you reopen this issue?

**Comment by bodgit** [comment]
This issue has been open for four years and nothing has apparently changed so I think it's unlikely this will ever be fixed, plus I'm not even using this tool these days.

I'll reopen for the benefit of anyone else.
