### ISSUE TITLE
container-diff requires server side API v1.39

### ISSUE THREAD

**Issue by morsedl** [GoogleContainerTools/container-diff#265]
### Expected behavior

Not having to be on the bleeding age to use container-diff. Official docker-ce releases (stable and edge) are still on API v1.38. I suppose I could build from sources, but that's could be quite some effort only to discover that API 1.39 is actually required by container-diff. Is it?

### Actual behavior

Container-diff fails because it is reporting API v1.39 to the server.

### Information

- container-diff version: Version 0.12.0 - 10/1/18
- Operating system: debian stretch (amd64)

### Steps to reproduce the behavior

```
# container-diff diff daemon://42bdaf9e6bc6 daemon://5772dc0624b7 --type=file
ERRO[0000] error retrieving image daemon://42bdaf9e6bc6: retrieving image from daemon: Error response from daemon: client version 1.39 is too new. Maximum supported API version is 1.38
error retrieving image daemon://5772dc0624b7: retrieving image from daemon: Error response from daemon: client version 1.39 is too new. Maximum supported API version is 1.38
```

**Comment by nkubala** [comment]
Hmm, yeah we should be trying to negotiate the API version before using the client/calling out to docker. I'll take a look
