### ISSUE TITLE
customize layer cache directory

### ISSUE THREAD

**Issue by vsoch** [GoogleContainerTools/container-diff#273]
Is there an environment variable to set the cache directory? As it is now, if I run this masse / in parallel all of the cache goes to my $HOME (which then poops out and dies because it would fill up immediately). I'd like to set the cache to be in an actual temporary directory so that this doesn't happen (and it's cleaned up when the job exist). It doesn't work to use --no-cache because I'll have about 1K running at once (and still will explode my $HOME). Thanks!

**Comment by nkubala** [comment]
Hey @vsoch, thanks for the issue. This is definitely something we could support, possibly with a CLI flag as well as an env var. Would you be interested in sending a PR?
