### ISSUE TITLE
Why doesn't this tool run in a container?

### ISSUE THREAD

**Issue by zfields** [GoogleContainerTools/container-diff#283]
### Information

- container-diff version: version...
- Operating system: ...

### Steps to reproduce the behavior

1. ...
2. ...

**Comment by nkubala** [comment]
Hey @zfields, there's no reason it *couldn't* run in a container, but without persistence caching in container-diff is impossible, so if you're planning on running container-diff on the same image multiple times it wouldn't make much sense. The container would also need to have docker in it so it could mount in the image(s) being processed, and I consider running docker-in-docker an antipattern.

In theory, nothing is stopping you from creating a container with the necessary dependencies and `container-diff` as the entrypoint, but as is the case with many standalone tools, I'm not sure what all you gain by doing that.

**Comment by nkubala** [comment]
container-diff has no dependencies, it's a standalone tool. You can install it using the install command for your platform that we provide on the homepage, and it will work out of the box.
