### ISSUE TITLE
CLI help should list available differ types

### ISSUE THREAD

**Issue by cben** [GoogleContainerTools/container-diff#293]
### Expected behavior
Having installed the tool, I tried to use its `--help` to see how to use it.  By default it only showed Size difference so I figured I need `--type`.  But what values can I use there?
Ideally `container-diff diff --help` and `container-diff help diff` would list available differ/analyzer types.
Or point to another command that would list them (eg. `container-diff help analyzers` or `container-diff diff --type help` or whatever).

### Actual behavior
```bash
$ container-diff help diff
Compares two images using the specifed analyzers as indicated via flags (see documentation for available ones).
...
  -t, --type Diff Types    This flag sets the list of analyzer types to use. Set it repeatedly to use multiple analyzers.
```

### Information

- container-diff version: `go get` from current master, v0.14.0-23-g 5b5e627
  BTW, you don't have a `--version` flag, making this question hard to answer :)
- Operating system: linux, fedora 29

**Comment by nkubala** [comment]
@cben thanks for the issue. the README does have a list of supported differs in the tool, but you're right it would be a nicer UX to have it supported through the `--help` flag.

would you be interested in sending a short PR to add this into the `help` command?

also, `container-diff version` (subcommand, not a flag) should do the trick :)
