### ISSUE TITLE
container can not be inspected.

### ISSUE THREAD

**Issue by gudrutis** [GoogleContainerTools/container-diff#294]
### Expected behavior

Getting  info.

### Actual behavior

Nothing is returned.
```
sudo container-diff analyze cmssw/docker-lxr:v0 --type=history --type=file --type=size --type=rpm --type=pip --type=apt --type=node  --type=apt
Password:
ERRO[0002] error getting analysis with HistoryAnalyzer: unsupported status code 404; body: 404 page not found
ERRO[0002] Could not detect RPM binary in unpacked image cmssw/docker-lxr:v0
ERRO[0002] error getting analysis with PipAnalyzer: unsupported status code 404; body: 404 page not found

-----Apt-----

Packages found in cmssw/docker-lxr:v0: None

-----File-----

Analysis for cmssw/docker-lxr:v0: None

-----Node-----

Packages found in cmssw/docker-lxr:v0: None

-----RPM-----

Packages found in cmssw/docker-lxr:v0: None

-----Size-----

Analysis for cmssw/docker-lxr:v0:
IMAGE                      DIGEST                                                                         SIZE
cmssw/docker-lxr:v0        sha256:1c8ab0360fead4142ffb1e6b291cdb6e6c40028c2696e2cdf7399c8956a06260        0

```

### Information

- container-diff version: latest version.
- Operating system: macOS, fedora26

**Comment by nkubala** [comment]
@gudrutis thanks for the issue. I'm not able to reproduce the `404` errors you're getting; I'm able to do a normal analysis on this image and get meaningful results for `history` and `file`; `rpm` fails since the binary doesn't exist in the image, and `pip` doesn't yield any results since no packages have been installed with pip in this image.

I'm running v0.14.0 to do this analysis on macOS, so probably similar environment to you. I was also able to run this successfully using `sudo`, though I have to ask, why are you trying to run as root?

maybe you can give me a little more info on your environment so I can get a successful repro of this?

**Comment by gudrutis** [comment]
@nkubala 
- I was running with `sudo` to check if it was an issue with permissions. Then I copy-pasted blindly and forgot about it.
- to be more specific, I am running macOS 10.14.2
- Attaching screanshot for docker enviroment.
Strange. It works fine on your machine? I ran it again with the same result.
I ran `container-difff` installation script to update to newest version, deleted all docker images and layers following [this tutorail](https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes), docker pull and I still have the same issue. Let me know what other information I can supply.
```
~ docker pull cmssw/docker-lxr:v0
v0: Pulling from cmssw/docker-lxr
892cc5bfc051: Pull complete
f3eda43ea55a: Pull complete
9466078d8996: Pull complete
44d770c1f7bd: Pull complete
1ce0c4bfe746: Pull complete
a3ed95caeb02: Pull complete
f3439edf8261: Pull complete
08bf1d42bd3d: Pull complete
4819089bfd29: Pull complete
965990681881: Pull complete
a334b133bcb3: Pull complete
a041351f9473: Pull complete
508a226389c3: Pull complete
05462c235c00: Pull complete
4979b518a5e1: Pull complete
7d898bc58422: Pull complete
Digest: sha256:b46ce45948ff3ccd26b845599a6e292215f424f06da78883cbe5f8f28b430f04
Status: Downloaded newer image for cmssw/docker-lxr:v0
➜  ~ container-diff analyze cmssw/docker-lxr:v0 --type=history --type=file --type=size --type=rpm --type=pip --type=apt --type=node  --type=apt
ERRO[0002] error getting analysis with HistoryAnalyzer: unsupported status code 404; body: 404 page not found
ERRO[0002] Could not detect RPM binary in unpacked image cmssw/docker-lxr:v0
ERRO[0003] error getting analysis with PipAnalyzer: unsupported status code 404; body: 404 page not found

-----Apt-----

Packages found in cmssw/docker-lxr:v0: None

-----File-----

Analysis for cmssw/docker-lxr:v0: None

-----Node-----

Packages found in cmssw/docker-lxr:v0: None

-----RPM-----

Packages found in cmssw/docker-lxr:v0: None

-----Size-----

Analysis for cmssw/docker-lxr:v0:
IMAGE                      DIGEST                                                                         SIZE
cmssw/docker-lxr:v0        sha256:21fb6b01456796c04a4f1d1d573fcb47b2c40b9ebe11f6290c2c075bc5819eb7        0
```

![screenshot 2019-03-01 at 19 58 43](https://user-images.githubusercontent.com/14026453/53659673-7212c000-3c5c-11e9-8950-2e4d6c1ecf72.png)
