### ISSUE TITLE
github release refers to wrong download URL

### ISSUE THREAD

**Issue by khrisrichardson** [GoogleContainerTools/container-diff#300]
### Expected behavior

The github release ought to point to the correct version to download

### Actual behavior

The github release for v0.14.0 and v0.15.0 points to the download URL for v0.13.1

### Information

- container-diff version: version...
- Operating system: ...

### Steps to reproduce the behavior

1. ...
2. ...

**Comment by nkubala** [comment]
🤦‍♂️ copy paste error on my part....fixed now.
