### ISSUE TITLE
ArchLinux Support

### ISSUE THREAD

**Issue by vsoch** [GoogleContainerTools/container-diff#301]
Hey Container Diff team!

@SantiagoTorres from the OCI list got equally excited about container-diff, and created a package for arch linux!

https://www.archlinux.org/packages/community/x86_64/container-diff/

Is this something that we can contribute for other arch linux users, or post somewhere on here?

**Comment by nkubala** [comment]
hey @vsoch and @SantiagoTorres! I'm all for this. what's the process for building the package and uploading to the distribution repo?

I'd be willing to consider a PR that adds support for this into our release process, as well as a small change to the readme that adds instructions for installing for arch linux.

**Comment by vsoch** [comment]
hey @nkubala I'll have to defer to @SantiagoTorres to share how he created that package - if he's claimed the namespace we might need to discuss how to transfer that.

**Comment by SantiagoTorres** [comment]
Hi @nkubala. I'll be taking care of packaging releases into the archlinux repositories, so no further action is needed :)

It'd however be nice to possibly mention it on the readme. Something like

> an Arch Linux package is readily available, to install just run:
> `pacman -S container-diff`

Or something of the like. I'll also be poking whenever we get a bugreport from users that can improve the tool for everyone :+1:

**Comment by nkubala** [comment]
@SantiagoTorres sorry I never got back to you on this one. did you ever resolve the issue with the namespace? I suppose it's not a huge deal if we don't own it.

I don't have an arch linux machine to test this on, but if you confirm you can install with `pacman` then feel free to send a PR to the README with install instructions :)

**Comment by vsoch** [comment]
@nkubala here is a container install:

```
$ docker run -it archlinux/base
[root@f32bde12d49a /]# pacman -Sy
:: Synchronizing package databases...
 core                                                                            133.7 KiB  1519K/s 00:00 [###############################################################] 100%
 extra                                                                          1690.6 KiB  4.01M/s 00:00 [###############################################################] 100%
 community                                                                         4.8 MiB  7.20M/s 00:01 [###############################################################] 100%
[root@f32bde12d49a /]# pacman -S container-diff
resolving dependencies...
looking for conflicting packages...

Packages (1) container-diff-0.15.0-1

Total Download Size:    2.82 MiB
Total Installed Size:  10.38 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 container-diff-0.15.0-1-x86_64                                                    2.8 MiB  5.73M/s 00:00 [###############################################################] 100%
(1/1) checking keys in keyring                                                                            [###############################################################] 100%
(1/1) checking package integrity                                                                          [###############################################################] 100%
(1/1) loading package files                                                                               [###############################################################] 100%
(1/1) checking for file conflicts                                                                         [###############################################################] 100%
(1/1) checking available disk space                                                                       [###############################################################] 100%
:: Processing package changes...
(1/1) installing container-diff                                                                           [###############################################################] 100%
:: Running post-transaction hooks...
(1/2) Cleaning up package cache...
(2/2) Arming ConditionNeedsUpdate...
```

It looks like `container-diff --help` doesn't print correctly (could that be an archlinux thing @SantiagoTorres?) 
```bash
[root@f32bde12d49a /]# container-diff --help
Usage of container-diff:
```
But the tool runs without `--help`
```bash
[root@f32bde12d49a /]# container-diff 
container-diff is a CLI tool for analyzing and comparing container images.

Images can be specified from either a local Docker daemon, or from a remote registry.
To specify a local image, prefix the image ID with 'daemon://', e.g. 'daemon://gcr.io/foo/bar'.
To specify a remote image, prefix the image ID with 'remote://', e.g. 'remote://gcr.io/foo/bar'.
If no prefix is specified, the local daemon will be checked first.

Tarballs can also be specified by simply providing the path to the .tar, .tar.gz, or .tgz file.

Usage:
  container-diff [command]

Available Commands:
  analyze     Analyzes an image: [image]
  diff        Compare two images: [image1] [image2]
  help        Help about any command
  version     Print the version of container-diff

Flags:
      --format string      Format to output diff in.
  -h, --help               help for container-diff
  -v, --verbosity string   This flag controls the verbosity of container-diff. (default "warning")

Use "container-diff [command] --help" for more information about a command.
```
Does it warrant any further testing? If not, we could just add the instruction to sync and then use pacman to install. I can offer to do a PR, if needed. Let me know your thoughts!

**Comment by SantiagoTorres** [comment]
@vsoch, I think this also happens with the release 0.15:

```
santiago at ~/.../GoogleContainerTools/container-diff ✗ mv ~/Downloads/container-diff-linux-amd64 .
santiago at ~/.../GoogleContainerTools/container-diff ✔ chmod +x container-diff-linux-amd64 
santiago at ~/.../GoogleContainerTools/container-diff ✔ ./container-diff-linux-amd64 --help
Usage of ./container-diff-linux-amd64:
```

**Comment by vsoch** [comment]
This looks unrelated to archlinux, here is a fresh install on Ubuntu 18.04:

```bash
root@3476377ca321:/# container-diff --help
Usage of container-diff:
```
Also in a container, I'll try on my machine too (16.04)

Yep, same bug! Let's ignore the --help, it's not related to ArchLinux (I'll open an issue for it if someone already hasn't). @SantiagoTorres do you want to do a PR to add the pacman install? I'm also happy to do this if you like! :)

**Comment by SantiagoTorres** [comment]
> @SantiagoTorres do you want to do a PR to add the pacman install? I'm also happy to do this if you like! :)

I can quickly sketch something. Thanks for reproducing! :+1:

**Comment by blueyed** [comment]
The README was changed in https://github.com/GoogleContainerTools/container-diff/pull/307 (https://github.com/GoogleContainerTools/container-diff/commit/d1003601ce26487cc0b37009100a4c51e054c631), and the bug was filed in https://github.com/GoogleContainerTools/container-diff/issues/306, so this can be closed.

**Comment by nkubala** [comment]
@blueyed thanks!
