### ISSUE TITLE
container-diff trying to pull images that are present on the host

### ISSUE THREAD

**Issue by mmodenesi** [GoogleContainerTools/container-diff#318]
### Expected behavior

do not try and pull images that are already locally available

### Actual behavior

trying to pull images from someware and failing due to authorization issues

### Information

- container-diff version: v0.15.0
- Operating system: ubuntu 19.04

### Steps to reproduce the behavior

1. install

```console
curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64 && chmod +x container-diff-linux-amd64 && sudo mv container-diff-linux-amd64 /usr/local/bin/container-diff
```
2.  use it

```console
container-diff diff 5a00b471a0c3 467490b19f1d                                                                                                                                                                         [17:39:30]
ERRO[0003] error retrieving image 5a00b471a0c3: UNAUTHORIZED: authentication required; [map[Type:repository Class: Name:library/5a00b471a0c3 Action:pull]]                                                                                                             
error retrieving image 5a00b471a0c3: UNAUTHORIZED: authentication required; [map[Type:repository Class: Name:library/5a00b471a0c3 Action:pull]]
```

It goes without saying, the images ids are correct and those correspond to images in my computer.

I've also tried with names and names + tags

**Comment by craneworks** [comment]
Use daemon://<image id/name/tag> to use local images instead of pulling.

**Comment by CodingSpiderFox** [comment]
For data protection reasons, I think daemon:// should be the default if nothing else is provided

**Comment by n1nj4-r4cc00n** [comment]
In my case @crane-denny suggestion didnt work, instead of using that format I used `daemon://<name>` which gave the proper result, it didn't work with the id or with the full suggestion

**Comment by EDIflyer** [comment]
I'm having this same issue trying to compare two local docker images...
``` bash
ediflyer@server:~$ sudo container-diff diff f9044c790295 5b3ff21ccf9e
2023/03/30 23:03:54 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2023/03/30 23:03:54 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
ERRO[0001] error retrieving image 5b3ff21ccf9e: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/5b3ff21ccf9e Type:repository]]
error retrieving image f9044c790295: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/f9044c790295 Type:repository]]
```
I then tried the `daemon://id/name/tag` nomenclature above (with variations) but still got an error?
``` bash
ediflyer@server:~$ sudo container-diff diff daemon://f9044c790295/jc21/nginx-proxy-manager daemon://5b3ff21ccf9e/jc21/nginx-proxy-manager
ERRO[0000] error retrieving image daemon://5b3ff21ccf9e/jc21/nginx-proxy-manager: retrieving image from daemon: Error response from daemon: reference does not exist
error retrieving image daemon://f9044c790295/jc21/nginx-proxy-manager: retrieving image from daemon: Error response from daemon: reference does not exist

ediflyer@server:~$ sudo container-diff diff daemon://f9044c790295/nginx-proxy-manager/latest daemon://5b3ff21ccf9e/nginx-pro
xy-manager/latest
ERRO[0000] error retrieving image daemon://5b3ff21ccf9e/nginx-proxy-manager/latest: retrieving image from daemon: Error response from daemon: reference does not exist
error retrieving image daemon://f9044c790295/nginx-proxy-manager/latest: retrieving image from daemon: Error response from daemon: reference does not exist
```

**Comment by EDIflyer** [comment]
So a workaround that seemed to do the trick for me was:

``` bash
docker save <containerid1> > container1.tar
docker save <containerid2> > container2.tar
container-diff diff container1.tar container2.tar --type=file
```

**Comment by uniuuu** [comment]
> I'm having this same issue trying to compare two local docker images...
> 
> ```shell
> ediflyer@server:~$ docker image ls | grep jc21
> jc21/nginx-proxy-manager           latest        f9044c790295   42 hours ago   842MB
> jc21/nginx-proxy-manager           <none>        5b3ff21ccf9e   3 days ago     842MB
> 
> ediflyer@server:~$ container-diff diff f9044c790295 5b3ff21ccf9e
> 2023/03/30 23:03:54 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
> 2023/03/30 23:03:54 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
> ERRO[0001] error retrieving image 5b3ff21ccf9e: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/5b3ff21ccf9e Type:repository]]
> error retrieving image f9044c790295: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/f9044c790295 Type:repository]]
> ```
> 
> I then tried the `daemon://id/name/tag` nomenclature above (with variations) but still got an error?
> 
> ```shell
> ediflyer@server:~$ container-diff diff daemon://f9044c790295/jc21/nginx-proxy-manager daemon://5b3ff21ccf9e/jc21/nginx-proxy-manager
> ERRO[0000] error retrieving image daemon://5b3ff21ccf9e/jc21/nginx-proxy-manager: retrieving image from daemon: Error response from daemon: reference does not exist
> error retrieving image daemon://f9044c790295/jc21/nginx-proxy-manager: retrieving image from daemon: Error response from daemon: reference does not exist
> 
> ediflyer@server:~$ container-diff diff daemon://f9044c790295/nginx-proxy-manager/latest daemon://5b3ff21ccf9e/nginx-pro
> xy-manager/latest
> ERRO[0000] error retrieving image daemon://5b3ff21ccf9e/nginx-proxy-manager/latest: retrieving image from daemon: Error response from daemon: reference does not exist
> error retrieving image daemon://f9044c790295/nginx-proxy-manager/latest: retrieving image from daemon: Error response from daemon: reference does not exist
> ```

It's working with next syntax: `container-diff diff daemon://nameA:tagA daemon://nameA:tagB`

**Comment by EDIflyer** [comment]
> It's working with next syntax: `container-diff diff daemon://nameA:tagA daemon://nameA:tagB`

Thanks @uniuuu - I don't quite follow though - what should I used for `nameA` above? It can't be the image ID as this would be different for both but you seem to be using the same name but different tags. Also not sure that tag to add for those that are `<none>`?

For example for the following containers:
```
ediflyer@server:~$ docker image ls | grep squidfunk
squidfunk/mkdocs-material    latest        de6206cf5330   13 days ago    139MB
squidfunk/mkdocs-material    <none>        30a4e7153144   6 weeks ago    139MB
```
I then tried the following (as expected `<none>` wasn't liked but I couldn't get it to work when trying other bits either:
```
ediflyer@server:~$ container-diff diff daemon://mkdocs-material:latest daemon://mkdocs-material:<none>
-bash: syntax error near unexpected token `newline'

ediflyer@server:~$ container-diff diff daemon://mkdocs-material:latest daemon://mkdocs-material:none
ERRO[0000] error retrieving image daemon://mkdocs-material:none: retrieving image from daemon: Error response from daemon: reference does not exist
error retrieving image daemon://mkdocs-material:latest: retrieving image from daemon: Error response from daemon: reference does not exist

ediflyer@server:~$ container-diff diff daemon://de6206cf5330:latest daemon://30a4e7153144:<none>
-bash: syntax error near unexpected token `newline'

ediflyer@server:~$ container-diff diff daemon://de6206cf5330:latest daemon://30a4e7153144:none
ERRO[0000] error retrieving image daemon://de6206cf5330:latest: retrieving image from daemon: Error response from daemon: reference does not exist
error retrieving image daemon://30a4e7153144:none: retrieving image from daemon: Error response from daemon: reference does not exist
```
