### ISSUE TITLE
Provide official docker-image

### ISSUE THREAD

**Issue by schnatterer** [GoogleContainerTools/container-diff#322]
### Expected behavior

A ready to run docker image containing `container-diff` on DockerHub or GCR or another public registry.
Allows for using `container-diff` conveniently via `docker run` without prio installation.

### Actual behavior

`container-diff` must be installed locally manually before it can be used.

### Information

There is an [inofficial image on DockerHub](https://hub.docker.com/r/gridx/container-diff) but can it be trusted?

**Comment by nkubala** [comment]
@schnatterer thanks for opening this issue. I'm not sure where that unofficial image came from, but we're not providing it. our team doesn't have much engineering bandwidth to wire this up right now, but if we ever have spare cycles I'll try and get to it.
