### ISSUE TITLE
Panic: Concurrent Map Writes

### ISSUE THREAD

**Issue by cvgw** [GoogleContainerTools/container-diff#323]
### Expected behavior
`container-diff diff` does not panic due to concurrent map writes

### Actual behavior

https://github.com/GoogleContainerTools/container-diff/blob/bca8ca4edd015e66f7da6e684f99af2f45813894/cmd/diff.go#L118
Will cause a panic due to concurrent map writes 

This is because `processImage` is called in two goroutines. 
`processImage` eventually calls `util.unpackTar` which has unsynchronized access to `util.hardlinks`

https://github.com/GoogleContainerTools/container-diff/blob/bca8ca4edd015e66f7da6e684f99af2f45813894/pkg/util/tar_utils.go#L137

### Information

- container-diff version: I'm trying to figure this out (it's the kaniko kokoro build)
- Operating system: I'm trying to figure this out (it's the kaniko kokoro build)

### Steps to reproduce the behavior
1. I haven't seen this error locally; only in the kaniko kokoro build

**Comment by nkubala** [comment]
@cvgw thanks for the issue. our team doesn't really have the engineering bandwidth to fix this issue right now, but contributions are certainly welcome. this should be fixable by using a `SyncMap`
