### ISSUE TITLE
Migrate base code to 1.13

### ISSUE THREAD

**Issue by antechrestos** [GoogleContainerTools/container-diff#328]
Hello

Would it be doable to migrate base code to golang 1.13? It may be usefull to migrate to go mod too. 
@nkubala I can do it myself.

**Comment by nkubala** [comment]
@antechrestos yeah absolutely. in fact, go 1.14 was just released yesterday, if you want to skip directly to that I'm fine with that too.

**Comment by antechrestos** [comment]
@nkubala great!
