### ISSUE TITLE
Is not having a checksum option an explicit decision?

### ISSUE THREAD

**Issue by erick-thompson** [GoogleContainerTools/container-diff#334]
I was hoping to use this tool to determine if two images had different filesystems. I can use the file analyzer, but that doesn't catch all changes to files, only changes that change size. For example, if there was a file named "environment.txt" that contained "test" in one image, and "prod" in another, they would show up as the same.

This seems like a super common use case for a diff tool. Was this not included for a reason? If not, any objections to adding something like this?

**Comment by nkubala** [comment]
@erick-thompson thanks for the issue. nope this just seems like a naive implementation - it probably caught all of our use cases at the time, but what you're suggesting seems more robust. contributions certainly welcome!
