### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by russellgan** [GoogleContainerTools/container-diff#336]
**Expected behavior**
container-diff diff daemon://<local_image1> daemon://<local_image2> --type=file 

**Actual behavior**
fails with fatal error

**Steps to reproduce the behavior**
container-diff diff daemon://<local_image1> daemon://<local_image2> --type=file 

I know a lot people have the same issue.So does anyone know other tools like container-diff which can explore file tree and export.PLEASE TELL ME!thanks a lot!!!

**Comment by nkubala** [comment]
@russellgan thanks for the issue. could you provide a little more detail on the image you're trying to run on? I'd love to be able to repro this so we can figure out a way to fix the problem.

**Comment by russellgan** [comment]
@nkubala thank you for replying.The image I compare is a private image from the company i am working at.So I'm sorry i can't give you more detail about it.But what I can tell you is size of image is about 5g.And before analyzing there is around 12g free memory,but still not enough.To be honest,I deeply doubt if this could be a problem caused by tool itself.

**Comment by vDMG** [comment]
Hello, i'm having the exact same issue on my side

**Comment by jessicah** [comment]
If it helps, this happened for me with discourse/base for a repro, but my machine is also memory constrained (4gig total)

**Comment by fxpester** [comment]
just got hit by the same error, OOM
