### ISSUE TITLE
Binary releases for arm64

### ISSUE THREAD

**Issue by odidev** [GoogleContainerTools/container-diff#338]
### Expected behavior
Is there any plan to release a container-diff binary for linux-arm64?

I have successfully created the binary for container-diff by running “go build -o container-diff”.

It will be very helpful if arm64 binaries are released. If any help is required in releasing them, I am happy to help. May I know the process which is followed for the binary release?

### Actual behavior
Container-diff binary is available for amd64 only.

**Comment by nkubala** [comment]
@odidev we probably won't be able to add this ourselves, but any help would certainly be appreciated!

you should be able to closely follow the [Makefile in Skaffold](https://github.com/GoogleContainerTools/skaffold/blob/master/Makefile) to get these binaries built on release. let me know if you need other pointers.
