### ISSUE TITLE
Compare labels

### ISSUE THREAD

**Issue by felipecrs** [GoogleContainerTools/container-diff#352]
Ultimately it would be good if we could compare the labels between images. My use case is:

I'm rewriting a very big Dockerfile here, and I don't want to introduce any breaking change by mistake, while changes in labels are one of them.

**Comment by nkubala** [comment]
@felipecrs thanks for the idea! I probably won't be able to get to adding this anytime soon since I'm not actively working on this project anymore, but contributions are certainly welcome if you'd like to take a stab at adding it!

**Comment by MPV** [comment]
Have you tried `Container Structure Test` for this? Has proven helpful for me in this regard.
