### ISSUE TITLE
Feature Request: Include file ownership in files analyzer

### ISSUE THREAD

**Issue by hown3d** [GoogleContainerTools/container-diff#377]
### Background
I'm working on user permissions for the kaniko builder (https://github.com/GoogleContainerTools/kaniko/pull/2106) and wanted to check if the ownership of a file is set correctly by using `--chown` flag on COPY statements.

Using container-diff there is currently no way to get the file ownership information.

Would probably go into this function in the files analyzer: https://github.com/GoogleContainerTools/container-diff/blob/bea7ad91741636770a9ed99b60b3bd416d057e34/pkg/util/fs_utils.go#L120-L132

**Comment by hown3d** [comment]
After some investigation this seems to be difficult to achieve:

Currently, the tar archive gets unpacked without reconstructing the ownership.
This is kind of difficult permissions wise, because to reconstruct, container-diff would need to be as run root

**Comment by Dhehowns** [comment]
What is actually compared beyond the file size? I can’t find that anywhere and the reports doesnt say.
