### ISSUE TITLE
A change is detected in the file system diff, however the two files are the same

### ISSUE THREAD

**Issue by Dhehowns** [GoogleContainerTools/container-diff#380]
### Expected behavior

Jar files in the two images should be the same

### Actual behavior

container-diff reports a difference 

### Information

The diff report is not debugguble. It reports a difference in size with the displayed size truncated to Megabytes 

It also doesnt dump the files that are being compared. This can help in reviewing the change properly.

**Comment by isqjw** [comment]
try container-diff diff -n ...
