### ISSUE TITLE
Track usage statistics

### ISSUE THREAD

**Issue by cftorres** [GoogleContainerTools/container-diff#9]
We should try and set up some infrastructure to track things like downloads, 7-day active users, etc.

Monitoring downloads will be related to where the release is stored and won't be inside of container-diff itself. Something like 7-day active users will need to be built into the tool. You can look at how minikube does something like this here:
https://github.com/kubernetes/minikube/blob/master/pkg/minikube/notify/notify.go

**Comment by kimsterv** [comment]
Add a user-agent.
